/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: funcubelibwrap.i

#ifndef SWIG_funcubelibwrap_WRAP_H_
#define SWIG_funcubelibwrap_WRAP_H_

class Swig_memory;

class SwigDirector_CallbackShim : public CallbackShim
{
 public:
  SwigDirector_CallbackShim(int swig_p);
  virtual ~SwigDirector_CallbackShim();
  void _swig_upcall_run() {
    CallbackShim::run();
  }
  virtual void run();
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
